- name: Run PostgreSQL database
  community.docker.docker_container:
    name: database
    image: mohaguef/tp-devops-database:latest
    pull: yes
    env_file: /home/admin/.env  # Use the copied .env file
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: db-network
    restart_policy: unless-stopped
