- name: Run Frontend Container
  community.docker.docker_container:
    name: frontend
    image: mohaguef/tp-devops-frontend:latest  # Replace with your actual image name
    pull: yes
    networks:
      - name: proxy-network
    restart_policy: unless-stopped
