- name: Create Docker network
  community.docker.docker_network:
    name: proxy-network
    driver: bridge

- name: Create Docker network
  community.docker.docker_network:
    name: db-network
    driver: bridge