- name: Run Simple API
  community.docker.docker_container:
    name: simple-api
    image: mohaguef/tp-devops-simple-api:latest
    pull: yes
    env_file: /home/admin/.env  # Use the copied .env file
    networks:
      - name: proxy-network
      - name: db-network
    restart_policy: unless-stopped
