- name: Run Simple API
  community.docker.docker_container:
    name: simple-api
    image: mohaguef/tp-devops-simple-api
    env:
      DATABASE_HOST: database
      DATABASE_NAME: db
      DATABASE_USER: usr
      DATABASE_PASSWORD: pwd
      DATABASE_URL: jdbc:postgresql://database:5432/db
    networks:
      - name: my-network
    restart_policy: unless-stopped
    ports:
      - "8080:8080"
