- name: Run Reverse Proxy
  community.docker.docker_container:
    name: reverse_proxy
    image: mohaguef/tp-devops-http-server:latest
    pull: yes
    ports:
      - "80:80"
    networks:
      - name: proxy-network
    restart_policy: unless-stopped
