name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Test Backend"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: github.event.workflow_run.conclusion == 'success'  # Exécute uniquement si les tests passent
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6.13.0
        with:
          context: simple-api
          tags: ${{ secrets.DOCKER_USER }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6.13.0
        with:
          context: database
          tags: ${{ secrets.DOCKER_USER }}/tp-devops-database:latest
          push: true

      - name: Build and push HTTP server image
        uses: docker/build-push-action@v6.13.0
        with:
          context: http-server
          tags: ${{ secrets.DOCKER_USER }}/tp-devops-http-server:latest
          push: true

      - name: Build and push frontend image
        uses: docker/build-push-action@v6.13.0
        with:
          context: front-main
          tags: ${{ secrets.DOCKER_USER }}/tp-devops-frontend:latest
          push: true