name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api


  build-and-push-docker-image:
    needs: test-backend  # Ensures tests pass before running this job
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCK_USER }}
          password: ${{ secrets.DOCK_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6.13.0
        with:
          context: simple-api
          tags: ${{ secrets.DOCK_USER }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}  # Only push if on main branch

      - name: Build image and push database
        uses: docker/build-push-action@v6.13.0
        with:
          context: database
          tags: ${{ secrets.DOCK_USER }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6.13.0
        with:
          context: http-server
          tags: ${{ secrets.DOCK_USER }}/tp-devops-http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}